### PR TITLE
Add chat bubble testimonial

### PR DESCRIPTION
**Pull request by paked**
This PR changes the design around our testimonials to be `chat bubble orientated`. It's this super hip new design trend. TLDR: put everything in a chat bubble.

Initial design on desktop:

screenshot 2017-02-15 14 31 50

Initial design on mobile:

screenshot 2017-02-15 14 31 14

Relevant Slack discussion:

> **harrison** [2:35 PM] 
> @zrl @msw: thoughts on the design here?
> 
> **zrl** [2:41 PM] 
> not a fan
> what if you did rounded corners, filled in the entire text bubble with white, and made he text black?
>
> **harrison** [2:42 PM] 
> personally, i thought that looked weird – most of the other corners on our site are hard.
> i’ll try that now
>
> **zrl** [2:42 PM] 
> and then also flipped the triangle in the bottom right to face the profile picture
> yeah, that's fair
> @msw will probably have way better feedback than me

I'd appreciate any feedback on the design.

### CODE REVIEW

**Comment by paked** [comment]
Zach's 2.0 specialty version:

Mobile: 
screenshot 2017-02-15 16 22 25

Desktop:
screenshot 2017-02-15 16 12 12

**Comment by zachlatta** [comment]
Bad example (I'm terrible at design), but hopefully this provides a better idea of what I'm trying to suggest.

**Comment by zachlatta** [comment]
frame

**Comment by paked** [comment]
@zachlatta: I don't know how I feel about that. The round borders look kind of weird with our current site which predominately features square edges.

**Comment by paked** [comment]
screenshot 2017-02-15 17 29 14

**Comment by MaxWofford** [comment]
@paked How would it look with an ending quote?

**Comment by MaxWofford** [comment]
@paked What's the status on this?

**Comment by MaxWofford** [comment]
Going to close this because there hasn't been recent activity. Feel free to re-open!

**Pull request closed without merging**
